### ISSUE TITLE
PR proposal and Pypi available

### ISSUE THREAD

**Issue by damdam-s** [skarra/pyews#1]
Hello @skarra,

I made some improvements of this library that you can find here: https://github.com/damdam-s/pyews/tree/setup_complete
Those improvements consist in the following things:
- support full contact fields (including physical addresses, phones, ...)
- support "quasi"-full calendar fields

To do this the cleanest possible, I refactored some of your work because both `Contact` and `Calendar` items can be inherited from `Item` class.

I wanted to ask you some questions:
1. Do I have to make a PR to your project ? (e.g: are you interested in those features ?)
2. As I created an installer for this library, can I push it to `pypi` ?
3. If you are not interested in it, can I still use the name `PyEWS` or do I have to change it ?

Thanks in advance,

Best regards,

@damdam-s

**Comment by skarra** [comment]
Hey Damien, thanks a lot for this. 

The changes you propose all look fantastic in theory. Please make a PR. I am happy to review and merge them in.  I would like my repo to be the main repo for this (to keep confusion low).

Let's plan to push this out to pypi after your changes are merged?

**Comment by damdam-s** [comment]
Hi @skarra,

Thanks for your answer. 
Please find the PR here: #2 . I made it against `master` but tell me if i should make another one against another branch.
No problems for you to still holding the repo :smile: .
Thanks in advance for the review.

Best regards,

@damdam-s

**Comment by skarra** [comment]
@damdam-s Thanks for quickly raising the PR. This is a lot of work, so I will take a bit to review and merge.

Thanks, again, for the contribution!

**Comment by damdam-s** [comment]
@skarra Thanks. I'm still working on it to make some things more generic like server_version in the soap header that I fixed to "Exchange2010_SP2" and other things.
For the calendar events, my code using this library sends UTC datetime with the following format `YYYY-mm-ddTHH:MM:SS.000Z` but i'm experincing some issues with event creation (seems to be timezone related). I'm still investigating on this point.
Regards,

**Comment by skarra** [comment]
@damdam-s You may have noticed that I have been reviewing and cherry-picking some of the commits from your PR. I am halting the process for now. Normally I would like to retain commit history, but in this case that does not look like a great option because there are numerous bugs / intermediate code changes that are fixed / reverted by your other commits, making overall review on a piece-meal basis very hard.

Can you complete all your work and then raise following pull requests:

(a) one for your calendar work
(b) one for your pypi / setup work
(c) one for your contact fields support work?

The minor debugging and other improvements can be squeezed in anywhere. Also please attention to the coding conventions I have pointed out in one of the commit comments.

**Comment by skarra** [comment]
Just so I am clear - I am trying to reduce the amount of review work for me, and also the amount of work for you to rebase your own branch to master once I am done integrating your changes.

Thanks again for working on this stuff.

**Comment by audreypapin** [comment]
Bonjour à vous, 

@damdam-s  je me permets de vous contacter. J'essaye d'installer le connecteur Exchange pour Odoo V10.
Mais je rencontre actuellement des difficultés sur l'installation préalable de Pyews. 

```
Traceback (most recent call last):
  File "misc.py", line 5, in <module>
    from pyews import WebCredentials, ExchangeService
ImportError: No module named pyews
```

Peut être y a t'il un élément qui m'échappe ?

**Comment by skarra** [comment]
Given that EWS itself is frozen, and BasicAuth will be blocked going forward, I am giving up on any future plan to catchup with your changes and basically giving up on this repo.

*Reference*:
https://techcommunity.microsoft.com/t5/exchange-team-blog/upcoming-changes-to-exchange-web-services-ews-api-for-office-365/ba-p/608055
